# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'squadifier2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import platform, subprocess, os
from functools import partial
from PyQt5 import QtCore, QtGui, QtWidgets
from genAlg import *
from generaRisultati import generaRisultati
from scriviRisultati import *

bambini = []
_translate = QtCore.QCoreApplication.translate

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(678, 496)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.titleLbl = QtWidgets.QLabel(Dialog)
        self.titleLbl.setGeometry(QtCore.QRect(170, 10, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setObjectName("titleLbl")
        self.parrocchiaLbl = QtWidgets.QLabel(Dialog)
        self.parrocchiaLbl.setGeometry(QtCore.QRect(20, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.parrocchiaLbl.setFont(font)
        self.parrocchiaLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.parrocchiaLbl.setObjectName("parrocchiaLbl")
        self.seiOttoLbl = QtWidgets.QLabel(Dialog)
        self.seiOttoLbl.setGeometry(QtCore.QRect(130, 120, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.seiOttoLbl.setFont(font)
        self.seiOttoLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seiOttoLbl.setObjectName("seiOttoLbl")
        self.noveDieciLbl = QtWidgets.QLabel(Dialog)
        self.noveDieciLbl.setGeometry(QtCore.QRect(120, 150, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.noveDieciLbl.setFont(font)
        self.noveDieciLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.noveDieciLbl.setObjectName("noveDieciLbl")
        self.undiciDodiciLbl = QtWidgets.QLabel(Dialog)
        self.undiciDodiciLbl.setGeometry(QtCore.QRect(110, 180, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.undiciDodiciLbl.setFont(font)
        self.undiciDodiciLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.undiciDodiciLbl.setObjectName("undiciDodiciLbl")
        self.trediciLbl = QtWidgets.QLabel(Dialog)
        self.trediciLbl.setGeometry(QtCore.QRect(130, 210, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.trediciLbl.setFont(font)
        self.trediciLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trediciLbl.setObjectName("trediciLbl")
        self.aggiuntiLbl = QtWidgets.QLabel(Dialog)
        self.aggiuntiLbl.setGeometry(QtCore.QRect(70, 270, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.aggiuntiLbl.setFont(font)
        self.aggiuntiLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aggiuntiLbl.setObjectName("aggiuntiLbl")
        self.varLbl = QtWidgets.QLabel(Dialog)
        self.varLbl.setGeometry(QtCore.QRect(280, 270, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.varLbl.setFont(font)
        self.varLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.varLbl.setObjectName("varLbl")
        self.msgLbl = QtWidgets.QLabel(Dialog)
        self.msgLbl.setGeometry(QtCore.QRect(369, 250, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.msgLbl.setFont(font)
        self.msgLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.msgLbl.setObjectName("msgLbl")
        self.aggiungiBtn = QtWidgets.QPushButton(Dialog)
        self.aggiungiBtn.setGeometry(QtCore.QRect(232, 320, 191, 41))
        self.aggiungiBtn.setStyleSheet("border-radius: 10px; border: 1px solid rgba(105, 105, 105, 0.5); background-color: rgba(255, 255, 255, 0.5)")
        self.aggiungiBtn.setObjectName("aggiungiBtn")
        self.generaBtn = QtWidgets.QPushButton(Dialog)
        self.generaBtn.setGeometry(QtCore.QRect(230, 420, 191, 41))
        self.generaBtn.setStyleSheet("border-radius: 10px; border: 1px solid rgba(105, 105, 105, 0.5); background-color: rgba(0, 255, 0, 0.5)")
        self.generaBtn.setObjectName("generaBtn")
        self.numLbl = QtWidgets.QLabel(Dialog)
        self.numLbl.setGeometry(QtCore.QRect(170, 370, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.numLbl.setFont(font)
        self.numLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numLbl.setObjectName("numLbl")
        self.parrocchiaEdit = QtWidgets.QLineEdit(Dialog)
        self.parrocchiaEdit.setGeometry(QtCore.QRect(230, 70, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.parrocchiaEdit.setFont(font)
        self.parrocchiaEdit.setText("")
        self.parrocchiaEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.parrocchiaEdit.setObjectName("parrocchiaEdit")
        self.seiOttoEdit = QtWidgets.QLineEdit(Dialog)
        self.seiOttoEdit.setGeometry(QtCore.QRect(230, 120, 111, 21))
        self.seiOttoEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.seiOttoEdit.setObjectName("seiOttoEdit")
        self.noveDieciEdit = QtWidgets.QLineEdit(Dialog)
        self.noveDieciEdit.setGeometry(QtCore.QRect(230, 150, 111, 21))
        self.noveDieciEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.noveDieciEdit.setObjectName("noveDieciEdit")
        self.undiciDodiciEdit = QtWidgets.QLineEdit(Dialog)
        self.undiciDodiciEdit.setGeometry(QtCore.QRect(230, 180, 111, 21))
        self.undiciDodiciEdit.setObjectName("undiciDodiciEdit")
        self.trediciEdit = QtWidgets.QLineEdit(Dialog)
        self.trediciEdit.setGeometry(QtCore.QRect(230, 210, 111, 21))
        self.trediciEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.trediciEdit.setObjectName("trediciEdit")
        self.numEdit = QtWidgets.QLineEdit(Dialog)
        self.numEdit.setGeometry(QtCore.QRect(390, 370, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.numEdit.setFont(font)
        self.numEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.numEdit.setText("")
        self.numEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.numEdit.setObjectName("numEdit")
        self.actionaggiungi = QtWidgets.QAction(Dialog)
        self.actionaggiungi.setObjectName("actionaggiungi")
        self.actiongenera = QtWidgets.QAction(Dialog)
        self.actiongenera.setObjectName("actiongenera")

        self.retranslateUi(Dialog)
        self.aggiungiBtn.clicked.connect(self.aggiungi) # type: ignore
        self.generaBtn.clicked.connect(self.genera) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def aggiungi(self, Dialog):
        parrocchia = str(self.parrocchiaEdit.text())
        try:
            seiOtto = int(str(self.seiOttoEdit.text()))
            noveDieci = int(str(self.noveDieciEdit.text()))
            undiciDodici = int(str(self.undiciDodiciEdit.text()))
            tredici = int(str(self.trediciEdit.text()))

            somma = seiOtto + noveDieci + undiciDodici + tredici
        except ValueError:
            self.msgLbl.setStyleSheet('color: red')
            self.msgLbl.setText(_translate('Dialog', '<b>Informazioni incorrette</b>'))
            return
        # Controlliamo che siano state inserite tutte le informazioni
        
        for _ in range(seiOtto):
            bambini.append({'parrocchia': parrocchia, 'eta': 6})
        for _ in range(noveDieci):
            bambini.append({'parrocchia': parrocchia, 'eta': 9})
        for _ in range(undiciDodici):
            bambini.append({'parrocchia': parrocchia, 'eta': 11})
        for _ in range(tredici):
            bambini.append({'parrocchia': parrocchia, 'eta': 13})

        self.msgLbl.setText(_translate('Dialog', '<b>Parrocchia aggiunta correttamente!</b>'))
        self.msgLbl.setStyleSheet('color: green')

        self.parrocchiaEdit.clear()
        self.seiOttoEdit.clear()
        self.noveDieciEdit.clear()
        self.undiciDodiciEdit.clear()
        self.trediciEdit.clear()

        bambiniAttuali = int(str(self.varLbl.text()))
        self.varLbl.setText(_translate('Dialog', str(bambiniAttuali + somma)))

    def genera(self, Dialog):
        try:
            squadNum = int(str(self.numEdit.text()))
        except ValueError:
            self.msgLbl.setStyleSheet('color: red')
            self.msgLbl.setText(_translate('Dialog', '<b>Numero squadre incorretto</b>'))
            return
        
        squadre = suddividi_bambini(bambini=bambini, numero_squadre=squadNum)
        testo = generaRisultati(squadre)

        # Controllo della piattaforma, per scegliere come salvare il file.
        if platform.system() == 'Darwin':
            filepath = scriviMacOS(squadNum, testo)
        elif platform.system() == 'Windows':
            filepath = scriviWindows(squadNum, testo)
        print('Filepath: {}'.format(filepath))
        
        # Aggiornamento finestra di dialogo.
        self.msgLbl.setText(_translate("Dialog", "<b><a href={}>Squadre generate! Clicca qui per aprire il file</a></b>".format(filepath)))
        self.msgLbl.linkActivated.connect(partial(self.startFile, '{}'.format(filepath)))
        self.parrocchiaEdit.clear()

    def startFile(self, filepath):
        if platform.system() == 'Darwin':       # macOS
            subprocess.call(('open', filepath))
        elif platform.system() == 'Windows':    # Windows
            os.startfile(filepath)
        else:                                   # linux variants
            subprocess.call(('xdg-open', filepath))

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Squadifier2"))
        self.titleLbl.setText(_translate("Dialog", "Divisione in squadre"))
        self.parrocchiaLbl.setText(_translate("Dialog", "Parrocchia"))
        self.seiOttoLbl.setText(_translate("Dialog", "6-8 anni"))
        self.noveDieciLbl.setText(_translate("Dialog", "9-10 anni"))
        self.undiciDodiciLbl.setText(_translate("Dialog", "11-12 anni"))
        self.trediciLbl.setText(_translate("Dialog", "13 anni"))
        self.aggiuntiLbl.setText(_translate("Dialog", "Bambini aggiunti:"))
        self.varLbl.setText(_translate("Dialog", "0"))
        self.msgLbl.setText(_translate("Dialog", ""))
        self.aggiungiBtn.setText(_translate("Dialog", "Aggiungi parrocchia"))
        self.generaBtn.setText(_translate("Dialog", "Genera squadre"))
        self.numLbl.setText(_translate("Dialog", "Numero squadre:"))
        self.actionaggiungi.setText(_translate("Dialog", "aggiungi"))
        self.actiongenera.setText(_translate("Dialog", "genera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
